---
- hosts: all
  gather_facts: false
  become: yes

  handlers:
    - import_tasks: ansible_handlers.yml

  vars_files:
    - tf_ansible_vars_file.yml

  tasks:

    # A harmless task to as placeholder.
    - debug:
        var: ansible_python_interpreter


    - name: RHEL-07-02190 | Address space randomization
      sysctl:
        name: kernel.randomize_va_space
        value: "2"
        state: present
        reload: yes
        ignoreerrors: yes
      notify: reboot system
      tags:
        RHEL-07-02190
